spring.application.name=learny
spring.data.mongodb.uri=mongodb://localhost:27017/db_learnfy
openai.api.key=API_KEY
openai.api.url=https://api.openai.com/v1/chat/completions

spring.web.resources.add-mappings=true
server.error.include-message=always

jwt.secret=MinhaChaveSuperSecretaQuePrecisaSerLonga
jwt.expiration=3600000 
